packages/angular/src/lib/element-registry.ts
Adds `RootLayout` to element-registry. This is the changes required for `RootLayout` to work with Angular (https://github.com/NativeScript/NativeScript/pull/8980). This is dependent on Nativescript's `release/8.0.0` branch
=> feat: add RootLayout to element-registry

packages/angular/src/lib/cdk/tab-view/index.ts, packages/angular/src/lib/element-registry/common-views.ts, packages/angular/src/lib/nativescript-common.module.ts, packages/angular/src/lib/public_api.ts
TabView is missing from the implementation
Backports tabview as it was before (to be reviewed later)
Fixes #4.
=> fix: re-add TabView

apps/nativescript-demo-ng/package.json, apps/nativescript-demo-ng/src/tests/platform-filter-components.ts, apps/nativescript-demo-ng/tools/xplat-postinstall.js, packages/angular/src/lib/cdk/platform-filters/index.ts, packages/angular/src/lib/nativescript-common.module.ts, packages/angular/src/lib/public_api.ts
=> fix: readd platform filters

packages/angular/src/lib/cdk/list-view/list-view.component.ts
Also logs when we try to create a view without a valid template key
This fixes an edge case where if you set `nsTemplateKey` it won't create the default template, meaning not using a templateSelector will break the ListView.
Up to discussion: the previous integration would silently ignore missing keys and create the default template instead. Should we do the same, add a flag (`fallbackToDefaultTemplate`) or just do what this PR introduces (log as an error)?
=> fix(list-view): always set a default template

packages/zone-js/dist/core.ts, packages/zone-js/dist/index.ts, packages/zone-js/dist/nativescript-globals.ts, packages/zone-js/dist/pre-zone-polyfills.ts, packages/zone-js/dist/utils.ts
Zone uses a `for(prop in object)` to patch all class properties, but this doesn't work with es6 as class properties aren't enumerable. Since NativeScript is distributed in es6+ the FileReader polyfill doesn't get properly patched by zonejs
Use `Object.getOwnPropertyNames` instead, so FileReader is patched correctly.
Currently only MutationObserver, WebKitMutationObserver, IntersectionObserver, FileReader and legacy XMLHttpRequest  are patched this way. Of all of them, only FileReader is polyfilled by NativeScript (the legacy XMLHttpRequest patch is already disabled)
Fixes #14.
=> fix(zone.js): correctly patch es6 classes

apps/nativescript-demo-ng/src/app/modal/modal.component.html, apps/nativescript-demo-ng/src/app/modal/modal.component.ts, packages/angular/src/lib/legacy/directives/dialogs.ts, packages/angular/src/lib/views/utils.ts
NgViewRef would treat ContentView as a non-native view, but it has a native view associated by default.
Nested legacy dialogs using viewContainerRef would fail to open due to setting the wrong _ngDialogRoot
We no longer ignore ContentView and _ngDialogRoot now correctly points to the correct view.
**This PR doesn't need to be squashed**
Fixes #17.
=> Dialog fixes

packages/angular/src/lib/nativescript-ng-zone.ts, packages/zone-js/dist/events.ts
main thread functions aren't patched
main thread functions are now patched
Fixes/Implements/Closes #[Issue Number].
=> feat(zone.js): patch Utils threading functions

packages/angular/src/lib/cdk/list-view/list-view.component.ts
If using a component without a native layout wrapper (stacklayout/etc), {N}'s listview will wrap the component in a layout. Doing so will break change detection
We try to unwrap the view to fetch the stored template key
Fixes #30.
=> fix(list-view): try to unwrap component views

packages/angular/src/lib/legacy/router/page-router-outlet.ts
The `page-router-outlet` will stop working if a call with `clearHistory: true` was invoked prior
The `page-router-outlet` continues to work and respond to navigations even if `clearHistory: true` is called
fixes: #39
=> fix: skip ChildrenOutLetContexts destroy hook if outlet has been changed

packages/angular/src/lib/application.ts
Sometimes with angular 13 hmr will trigger a restart instead of a reload due to `module['hot']` not being replaced by webpack.
We use the new esm import.meta to get that information.
=> fix: use new import.meta.webpackHmr to account for esm

README.md, packages/angular/README.md, packages/angular/package.json, packages/angular/src/lib/legacy/router/ns-location-strategy.ts, packages/angular/src/lib/legacy/router/ns-location-utils.ts, packages/angular/src/lib/legacy/router/page-router-outlet.ts, packages/angular/src/lib/legacy/router/router-extensions.ts
We mark all outlet keys as being backed on.
We only mark keys that are of a higher nesting level than the current key as being backed on.
Fixes #49.
=> fix: restrict nested outlet back navigation scope

packages/angular/src/lib/legacy/router/ns-location-utils.ts, packages/angular/src/lib/legacy/router/page-router-outlet.ts
Fixes/Implements/Closes #[Issue Number].
=> fix: look for correct outlet to back to

packages/angular/src/lib/cdk/detached-loader.ts, packages/angular/src/lib/legacy/router/page-router-outlet.ts
this was a mistake from long ago
DetachedContainer was changed so it always attaches to ApplicationRef because 99% of the time we've been using it to create modals, which shouldn't be attached to a viewcontainer. Turns out we are also using it for pages, so we broke the page detaching when they were deactivated
DetachedContainer should be used carefully.
=> fix: load pages in location instead of in appRef

packages/angular/src/lib/nativescript-renderer.ts, packages/angular/src/lib/view-util.ts, packages/angular/src/lib/views/invisible-nodes.ts, packages/angular/src/lib/views/view-types.ts
TextNodes are ignored
Any invisible node can be supported (through the invisible node meta property). By default, when a TextNode is added to a view, it sets the `view.text` property and listen to any changes on the `TextNode` and reapplies the `text` property.
This allows for the very neat:
```
<Label>This works! {{ someProperty | async }}</Label>
```
=> feat: support adding TextNode elements (automatically sets text property by default)

packages/zone-js/dist/events.ts
the view showModal is not patched, so the close callback may not always return on the angular zone
We now patch the showModal method
=> fix: patch showModal call in zone

packages/angular/src/lib/view-util.ts, packages/angular/src/lib/views/utils.ts
This is a better fix for the RadListView issue people have been facing (infinite loop hanging the UI). We now handle the parentNode for all detached elements, as well as keeping a parentNode reference to manually detached elements so angular can correctly find it in our "logical" view tree
=> fix: better handling of parentNode on detached elements

packages/angular/src/lib/cdk/dialog/dialog-ref.ts, packages/angular/src/lib/cdk/dialog/native-modal-ref.ts, packages/angular/src/lib/legacy/directives/dialogs.ts, packages/angular/src/lib/legacy/router/ns-location-strategy.ts
Currently when a modal closes the events fire quickly, often before the modal has fully closed. As a result, navigations done directly on the afterClosed callback won't work, needing a 0ms delay on iOS and >100ms on Android.
We delay the afterClosed callback until we're sure the modal has fully closed
=> fix: modal beforeClosed and afterClosed consistency between platforms

packages/angular/src/lib/view-util.ts
This should finally solve the RLV issues. A bracket was put in the wrong place (probably during the refactor) and we'd break our linked list when removing the first child of a parent.
=> fix: correctly reassign siblings in linked list

packages/angular/package.json, packages/angular/src/lib/legacy/router/page-router-outlet.ts
=> fix: use correct EnvironmentalInjector in page-router-outlet

packages/angular/src/lib/cdk/dialog/native-modal-ref.ts, packages/angular/src/lib/legacy/directives/dialogs.ts
Turns out that the `detectChanges` doesn't actually detect changes (or maybe rather doesn't mark the component for change detection)
We force the change detection via `changeDetectorRef.detectChanges()`, which solves a few issues with CD being run AFTER the view is created and attached
=> fix: use changeDetectorRef.detectChanges() instead of detectChanges() private api

packages/angular/src/lib/legacy/router/ns-route-reuse-strategy.ts, packages/angular/src/lib/legacy/router/page-router-outlet.ts
When navigating with clearHistory, we delay clearing the history until `navigatedTo` fires so the previous page doesn't become blank before the navigation animation finishes. This has a side-effect that if we quickly navigate the cache clear might happen after the next navigation, clearing the cache in a wrong way.
We now force clear the cache on route detach or deactivate if it hasn't been cleared yet, before any other cache manipulation has happened
=> fix(router): fix navigation when clearing history and navigating before the navigatedTo event fires

packages/angular/src/lib/cdk/list-view/list-view.component.ts
We changed the ListViewComponent a while ago and it broke backwards compatibility for some plugins
We don't rely on `super()` calls anymore and instead use `inject()`
=> fix: use inject in ListViewComponent

apps/nativescript-demo-ng/src/tests/spans.spec.ts, apps/nativescript-demo-ng/src/tests/textnode.spec.ts, packages/angular/src/lib/element-registry/common-views.ts, packages/angular/src/lib/element-registry/metas.ts, packages/angular/src/lib/view-util.ts, packages/angular/src/lib/views/utils.ts
We currently fallback to _addChildFromBuilder for spans
We now implement a meta that correctly implements add/remove child spans
Fixes #65
=> fix: add meta for TextBase and FormattedString

packages/angular/src/lib/application.ts
=> feat: support embedded applications

packages/angular/src/lib/animations/animations.module.ts
Allow Angular 17 animations to work correctly
Correct https://github.com/NativeScript/angular/issues/125
=> Correct animations

packages/angular/src/lib/nativescript-renderer.ts, packages/angular/src/lib/public_api.ts, packages/angular/src/lib/tokens.ts, packages/angular/src/lib/utils/native-element-host.ts
This is a draft PR with a small change that would allow the user to prevent some events from firing during a DOM change (example: during change detection), so such events would only reach angular if they fire outside of CD (eg: during user interaction)
=> feat: allow tracking of dom changes and preventing events from firing during one

packages/angular/package.json, packages/angular/src/lib/platform-nativescript.ts
This enables all the browser features like `@defer`, `afterRender` and `afterNextRender`, which are integral parts of new updates (including the angular router in the future)
BREAKING CHANGES:
Identifying as browser can have minor impact on existing libraries that use that to manipulate the DOM. So far, the usage inside angular itself is minimal enough that it shouldn't impact apps other than enabling previously mentioned features.
=> feat: make nativescript identify as browser in angular
